### ISSUE TITLE
Fails to complile: Malfored number string

### ISSUE THREAD

**Issue by Wh1t3Rose** [melkor217/ayanami#9]
```
tyler@mysqlwebserv:~/Downloads/ayanami-master$ bundle install
Fetching source index from https://rubygems.org/
There was a ArgumentError while loading sinatra.gemspec: 
Malformed version number string 2.0.0-alpha from
/home/tyler/.bundler/ruby/1.9.1/sinatra-751f2a7a8f26/sinatra.gemspec:4:in
`new'
```

Now I am very new to Ruby. So I don't know how to fix this. Is this because one of the gemfiles has a wrong version string? What should I do?

**Comment by Sandman007** [comment]
Not sure if this would be of use but here is the contents of /.bundler/ruby/1.9.1/sinatra-751f2a7a8f26/sinatra.gemspec

`$LOAD_PATH.unshift File.expand_path('../lib', __FILE__)
require 'sinatra/version'

Gem::Specification.new 'sinatra', Sinatra::VERSION do |s|
  s.description       = "Sinatra is a DSL for quickly creating web applications in Ruby with minimal effort."
  s.summary           = "Classy web-development dressed in a DSL"
  s.authors           = ["Blake Mizerany", "Ryan Tomayko", "Simon Rozet", "Konstantin Haase"]
  s.email             = "sinatrarb@googlegroups.com"
  s.homepage          = "http://www.sinatrarb.com/"
  s.license           = 'MIT'
  s.files = %w(.yardopts AUTHORS.md CHANGELOG.md CONTRIBUTING.md Gemfile LICENSE MAINTENANCE.md Rakefile SECURITY.md sinatra.gemspec) + Dir['README*.md', 'lib/**/*', 'examples/*']
  s.test_files        = s.files.select { |p| p =~ /^test\/.*_test.rb/ }
  s.extra_rdoc_files  = s.files.select { |p| p =~ /^README/ } << 'LICENSE'
  s.rdoc_options      = %w[--line-numbers --inline-source --title Sinatra --main README.rdoc --encoding=UTF-8]

  s.required_ruby_version = '>= 2.2.0'

  s.add_dependency 'rack', '~> 2.0'
  s.add_dependency 'tilt', '~> 2.0'
  s.add_dependency 'rack-protection', '~> 1.5'
  s.add_dependency 'mustermann',  '~> 0.4'
end`

**Comment by Sandman007** [comment]
I had an older Ruby Version. My bad. I'm new so I didn't know. Got 2.2-dev for the header files. Everything Compiled.
